site_name: PHN Exchange Help Centre

theme: readthedocs
extra_css: 
    - css/extra.css

nav:
- Home: 'index.md'
- Overview: 'overview.md'
- Practices:
    - 'Viewing your GP Data Report' : 'practices/gp-data-report.md'
    - 'Viewing your GP License Agreements' : 'practices/gp-license-agreements.md'
- PHN Admins:
    - 'Adding Practice members' : 'phn-admin/practice-members.md'
    - 'Adding PHN regions': 'phn-admin/phn-regions.md'

markdown_extensions:
    - toc:
        permalink: "#"