site_name: PHN Exchange Help Centre

theme: readthedocs
extra_css: 
    - css/extra.css

nav:
- Home: 'index.md'
- General:
    - Overview: 'overview.md'
    - Minimum System Requirements: 'minimum.md'
    - Regulations: 'regulations.md'
    - Reports: 'reports.md'
    - Support: 'support.md'
    - Security: 'security.md'
    - Terms and Conditions: 'terms.md'
- Practices:
    - Engagement with Practices: 'engagement.md'
    - GP Data: 'gpdata.md'
    - PIP QI: 'pipqi.md'
    - EULA: 'eula.md'
    - Data Extraction: 'extraction.md'
- Components: 
    - ABS Atlas: 'atlas.md'
    - Customer Relationship Management: 'crm.md'
    - Learning Management System: 'lms.md'
    - Population Health: 'populationhealth.md'
    - Priority Areas: 'priority.md'
    - Admin: 'admin.md'
- User guides:
    - PHN Staff: 'practice-staff.md'

markdown_extensions:
    - toc:
        permalink: "#"
